# Site settings
title: "Mihai Grigore - Cloud Architect - Resume"
description: "Mihai Grigore - Cloud Architect - Resume 2023"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Mihai Grigore"
resume_title:                   "Cloud Architect"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "hello@motzu.ro"
resume_download:                "yes"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+40723.452.887"
resume_contact_address:         "Sibiu, Romania"

resume_header_contact_info:     "Sibiu, Romania • +40723.452.887 • hello@motzu.ro"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hello, I'm Mihai and I'm a Cloud Architect. I bring expertise in orchestrating strategic transitions from on-premise infrastructure to the cloud. Specializing in crafting robust cloud architectures, I contribute to enhancing organizational efficiency, scalability, and security. My role involves leveraging cutting-edge technologies like Terraform, GCP, Azure, and more to architect solutions that align with any business objectives. With a commitment to innovation and backed by certifications, including Professional Cloud Architect, I empower companies to embrace the full potential of cloud technology for a future-ready and competitive edge.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
#resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/this-is-mihai"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/this-is-mihai"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
